import { Inter, Epilogue } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata = {
  title: "FuturaEd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black ${inter.className} ${epilogue.className}`}>{children}</body>
    </html>
  );
}
